apiVersion: elasticweb.com.operator-example/v1
kind: ElasticWeb
metadata:
  labels:
    app.kubernetes.io/name: elasticweb
    app.kubernetes.io/instance: elasticweb-sample
    app.kubernetes.io/part-of: operator-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-example
  name: elasticweb-sample
spec:
  # TODO(user): Add fields here
