---
apiVersion: elasticweb.com.bolingcavalry/v1
kind: ElasticWeb
metadata:
  namespace: dev
  name: elasticweb-sample2
spec:
  # Add fields here
  image: tomcat:8.0.18-jre8
  port: 30004
  singlePodQPS: 500
  totalQPS: 800
